### ISSUE TITLE
Missing txt files?

### ISSUE THREAD

**Issue by sgfin** [bio-ontology-research-group/multi-drug-embedding#2]
Hello,

My apologies for a second question, but when I download the data.zip file, I see a file "diseases_text_embeddings.txt" and a file "drugs_text_embeddings.txt," but do not see a corresponding "genes_text_embeddings.txt".  Does this file exist?

Finally, would you be willing to share the "edgelist" files?  Given that the source ontologies are constantly changing, it seems like it'll be difficult to precisely recreate or compare to your work without them.  It also breaks the scripts to have references to files by name without having those files or a description of their format.

Best,
Sam

**Comment by monaalsh** [comment]
hello,
please download the files again, added all embeddings and edgelist files.

**Comment by sgfin** [comment]
Thank you!  I will close the issue and re-open if I have any issues after downloading the new files.

Thanks again for the quick response.  I hope your willingness to share means that your knowledge graph gets used and cited in many studies!
